[platformio]
src_dir = src

[env:esp32-s3-devkitc-1]
platform = espressif32 @ ^6.10.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_mode = opi
board_build.flash_size = 8MB
board_build.partitions = default_8MB.csv
board_build.filesystem = littlefs
lib_ignore = SPIFFS
build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D CORE_DEBUG_LEVEL=3

lib_deps =
			adafruit/Adafruit NeoPixel @ ^1.15.5
			h2zero/NimBLE-Arduino @ ^2.5.0
			madhephaestus/ESP32Servo @ ^3.2.1
			